name: Extract mrepol.zip

on:
  push:
    paths:
      - "mrepol.zip"

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Unzip Utility
      run: sudo apt-get install -y unzip

    - name: Extract ZIP File
      run: unzip mrepol.zip -d .

    - name: Show Extracted Files
      run: ls -R

    - name: Commit and Push Extracted Files
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Extracted contents of mrepol.zip"
        git push
